export default [
  {
    id: 1,
    headline: "მიიღე 300% ქეშბ...",
    text: "retrieve 300% bet amount as real money...",
    image: "/src/assets/Rounded Rectangle 595-1.png",
    colorClass: "blue-background",
    baseColor: "baseBlue",
  },
  {
    id: 2,
    headline: "მალე",
    text: "retrieve 300% bet amount as real money...",
    image: "/src/assets/Rounded Rectangle 595.png",
    colorClass: "orange-background",
    baseColor: "baseOrange",
  },
  {
    id: 3,
    headline: "მოიგე ჯეკპოტი",
    text: "retrieve 300% bet amount as real money...",
    image: "/src/assets/Rounded Rectangle 595-2.png",
    colorClass: "dark-blue-background",
    baseColor: "baseDark",
  },
  {
    id: 4,
    headline: "მიიღე 300% ქეშბ...",
    text: "retrieve 300% bet amount as real money...",
    image: "/src/assets/Rounded Rectangle 595-1.png",
    colorClass: "blue-background",
    baseColor: "baseBlue",
  },
  {
    id: 5,
    headline: "მალე",
    text: "retrieve 300% bet amount as real money...",
    image: "/src/assets/Rounded Rectangle 595.png",
    colorClass: "orange-background",
    baseColor: "baseOrange",
  },
  {
    id: 6,
    headline: "მოიგე ჯეკპოტი",
    text: "retrieve 300% bet amount as real money...",
    image: "/src/assets/Rounded Rectangle 595-2.png",
    colorClass: "dark-blue-background",
    baseColor: "baseDark",
  },
];
